[tool.poetry]
name = "store-crawl4ai"
version = "0.1.0"
description = ""
authors = ["Jan Buchar <jan.buchar@apify.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
apify = "^2.1.0"
crawl4ai = "^0.5.0"
pydantic = "^2.9.2"
crawlee = "~0.6.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.6.8"

[tool.basedpyright]
typeCheckingMode = "standard"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
